# Generated by Django 5.1.1 on 2024-10-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=150)),
                ('prenoms', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Monsieur', 'Mr'), ('Madam', 'Mm')], max_length=10, null=True)),
                ('emails', models.CharField(max_length=150)),
            ],
        ),
    ]
