# Generated by Django 5.1.1 on 2024-10-23 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('naissance', models.DateField()),
                ('genre', models.CharField(choices=[('Male', 'M'), ('Femme', 'F')], max_length=6, null=True)),
                ('email', models.CharField(max_length=150)),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formateur')),
            ],
        ),
    ]
