# Generated by Django 5.1.1 on 2024-10-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Elevage', 'Elevage'), ('Agricole', 'Agricole'), ('Transformation Produit', 'T-Produit'), ('Couper coutume', 'C-Coutume')], max_length=24, null=True)),
                ('dure', models.CharField(max_length=25)),
                ('prix', models.FloatField(default=0.0)),
            ],
        ),
    ]
