# Generated by Django 5.1.1 on 2024-10-24 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_formation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formateur',
            old_name='emails',
            new_name='e_mail',
        ),
        migrations.RenameField(
            model_name='formateur',
            old_name='gender',
            new_name='genr',
        ),
        migrations.RenameField(
            model_name='formateur',
            old_name='prenoms',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='formateur',
            old_name='noms',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Inscrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateTimeField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
