# Generated by Django 5.1.1 on 2024-10-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_emails_formateur_e_mail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formateur',
            old_name='name',
            new_name='names',
        ),
    ]
