# Generated by Django 5.1.1 on 2024-10-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_name_formateur_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='dure',
            field=models.CharField(max_length=40),
        ),
    ]
