# Generated by Django 5.1.1 on 2024-10-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_formation_dure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='dure',
            field=models.CharField(max_length=25),
        ),
    ]
