# Generated by Django 5.1.1 on 2024-10-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_inscrie_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrie',
            name='dates',
            field=models.DateField(),
        ),
    ]
